import type { Category, Condition, MarketplaceListing, Product } from "@/lib/types";
import { seedImage } from "@/lib/utils";

interface SeedProduct {
  sku: string;
  name: string;
  brand: string;
  category: Category;
  size: string;
  colour: string;
  material: string;
  condition: Condition;
  conditionNotes: string;
  measurements: [string, string][];
  description: string;
  defects?: string[];
  tags?: string[];
  price: number;
  compareAtPrice?: number;
  cost?: number;
  floorPrice?: number;
  status?: Product["status"];
  location?: string;
  listedAt: string;
  soldAt?: string;
  acquisitionSource?: string;
  purchaseDate?: string;
  isPick?: boolean;
  featured?: boolean;
  channels?: Partial<Record<"website" | "vinted" | "depop" | "ebay", boolean>>;
}

const DEFAULT_CHANNELS: MarketplaceListing[] = [
  { channel: "website", status: "LISTED" },
  { channel: "vinted", status: "NOT_LISTED" },
  { channel: "depop", status: "NOT_LISTED" },
  { channel: "ebay", status: "NOT_LISTED" },
];

function build(p: SeedProduct): Product {
  return {
    sku: p.sku,
    slug: `${p.sku.toLowerCase()}-${p.brand.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${p.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")}`,
    name: p.name,
    brand: p.brand,
    category: p.category,
    size: p.size,
    colour: p.colour,
    material: p.material,
    condition: p.condition,
    conditionNotes: p.conditionNotes,
    measurements: p.measurements.map(([label, value]) => ({ label, value })),
    description: p.description,
    defects: p.defects ?? [],
    tags: p.tags ?? [],
    price: p.price,
    compareAtPrice: p.compareAtPrice,
    cost: p.cost,
    floorPrice: p.floorPrice,
    images: Array.from({ length: 5 }, (_, i) => ({
      src: seedImage(`vc-${p.sku}-${i}`, 900, 1125),
      alt: `${p.brand} ${p.name} - image ${i + 1}`,
    })),
    status: p.status ?? "AVAILABLE",
    location: p.location,
    listedAt: p.listedAt,
    soldAt: p.soldAt,
    acquisitionSource: p.acquisitionSource,
    purchaseDate: p.purchaseDate,
    marketplace: DEFAULT_CHANNELS.map((m) => ({
      ...m,
      status: p.channels?.[m.channel] ? "LISTED" : m.status,
    })),
    isPick: p.isPick,
    featured: p.featured,
  };
}

const JACKET_MEASUREMENTS: [string, string][] = [
  ["Pit to pit", "23.5\""],
  ["Length", "26\""],
  ["Sleeve", "25\""],
];

const TROUSER_MEASUREMENTS: [string, string][] = [
  ["Waist", "32\""],
  ["Rise", "11.5\""],
  ["Inseam", "31\""],
];

const TOP_MEASUREMENTS: [string, string][] = [
  ["Pit to pit", "21\""],
  ["Length", "27\""],
  ["Sleeve", "24\""],
];

export function buildSeedProducts(): Product[] {
  return [
    build({
      sku: "VC-000381",
      name: "Detroit Jacket",
      brand: "Carhartt",
      category: "jackets",
      size: "M",
      colour: "Carhartt Brown",
      material: "12oz cotton duck",
      condition: "very_good",
      conditionNotes:
        "Light wear around the cuffs and hem. Blanket lining is intact with no holes or repairs.",
      measurements: JACKET_MEASUREMENTS,
      description:
        "The classic workwear icon, in the original 12oz duck canvas. Broken in exactly enough that it sits right, with years left in it. No branding changes, no fuss.",
      tags: ["workwear", "canvas", "carhartt-brown"],
      price: 64,
      cost: 18,
      floorPrice: 48,
      location: "A-04",
      listedAt: "2026-08-08T10:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-07-28",
      isPick: true,
      featured: true,
      channels: { website: true },
    }),
    build({
      sku: "VC-000412",
      name: "Box Logo Hoodie",
      brand: "Supreme",
      category: "hoodies",
      size: "L",
      colour: "Heather Grey",
      material: "Cotton fleece",
      condition: "excellent",
      conditionNotes: "Minimal wear. Print is sharp, no cracking or fading.",
      measurements: TOP_MEASUREMENTS,
      description:
        "FW22 heather grey box logo hoodie. Stored folded, print checked under light: no fade, no cracks. The one that never really got worn.",
      tags: ["streetwear", "fw22", "box-logo"],
      price: 185,
      cost: 110,
      floorPrice: 150,
      location: "A-01",
      listedAt: "2026-08-14T09:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-08-05",
      isPick: true,
      featured: true,
      channels: { website: true, depop: true },
    }),
    build({
      sku: "VC-000398",
      name: "Swoosh Hoodie",
      brand: "Nike",
      category: "hoodies",
      size: "M",
      colour: "Black",
      material: "80% cotton, 20% polyester",
      condition: "good",
      conditionNotes:
        "Small mark on the lower front (photographed). Slight pilling under the arms.",
      defects: ["Small mark on lower front", "Light pilling under arms"],
      measurements: TOP_MEASUREMENTS,
      description:
        "Everyday black Nike hoodie in the heavier weight. The mark is small enough to be invisible in most light, priced to reflect it.",
      tags: ["sportswear", "black", "everyday"],
      price: 28,
      cost: 9,
      floorPrice: 20,
      location: "B-12",
      listedAt: "2026-08-11T12:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-08-01",
      channels: { website: true, vinted: true },
    }),
    build({
      sku: "VC-000375",
      name: "Classic Fleece Half-Zip",
      brand: "Patagonia",
      category: "knitwear",
      size: "M",
      colour: "Navy",
      material: "Recycled polyester fleece",
      condition: "very_good",
      conditionNotes: "Light general wear, no pilling or fading.",
      measurements: TOP_MEASUREMENTS,
      description:
        "The fleece that made fleece acceptable. Deep navy, full zip is smooth, cuffs still snug.",
      tags: ["outdoor", "fleece", "navy"],
      price: 45,
      cost: 15,
      floorPrice: 34,
      location: "A-06",
      listedAt: "2026-07-30T14:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-07-20",
      channels: { website: true, ebay: true },
    }),
    build({
      sku: "VC-000402",
      name: "Arctic Parka",
      brand: "The North Face",
      category: "jackets",
      size: "L",
      colour: "Black",
      material: "Nylon shell, down fill",
      condition: "excellent",
      conditionNotes: "Worn a handful of times. Down loft intact.",
      measurements: JACKET_MEASUREMENTS,
      description:
        "Proper winter parka with real down fill. Checked every seam and zip — this one is basically new with the tags off.",
      tags: ["winter", "down", "parka"],
      price: 95,
      cost: 40,
      floorPrice: 70,
      location: "A-02",
      listedAt: "2026-08-16T08:30:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-08-10",
      isPick: true,
      channels: { website: true },
    }),
    build({
      sku: "VC-000388",
      name: "Painter's Double Knee",
      brand: "Carhartt WIP",
      category: "trousers",
      size: "32/32",
      colour: "Black",
      material: "Dearborn canvas",
      condition: "good",
      conditionNotes: "Fading at the knees and seat, no rips or repairs.",
      measurements: TROUSER_MEASUREMENTS,
      description:
        "Double knee work trousers from the WIP line. The fade is even and honest — these look better now than new.",
      tags: ["workwear", "canvas", "black"],
      price: 52,
      cost: 16,
      floorPrice: 38,
      location: "B-03",
      listedAt: "2026-08-06T11:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-07-26",
      channels: { website: true, depop: true },
    }),
    build({
      sku: "VC-000420",
      name: "501 Original Fit Jeans",
      brand: "Levi's",
      category: "jeans",
      size: "34/32",
      colour: "Mid Blue",
      material: "100% cotton denim",
      condition: "very_good",
      conditionNotes: "Light fading, original hem, no repairs.",
      measurements: TROUSER_MEASUREMENTS,
      description:
        "The 501 everyone keeps coming back to. Mid blue wash with an even fade and the original hem untouched.",
      tags: ["denim", "501", "classic"],
      price: 42,
      cost: 14,
      floorPrice: 30,
      location: "B-07",
      listedAt: "2026-08-13T13:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-08-02",
      channels: { website: true, vinted: true },
    }),
    build({
      sku: "VC-000367",
      name: "Air Force 1 Low",
      brand: "Nike",
      category: "footwear",
      size: "UK 9",
      colour: "Triple White",
      material: "Leather upper, rubber sole",
      condition: "good",
      conditionNotes: "Creasing to toe box, some scuffs on the sole. Cleaned and deodorised.",
      defects: ["Toe box creasing", "Sole scuffs"],
      measurements: [
        ["UK size", "9"],
        ["Insole length", "27.5cm"],
      ],
      description:
        "Triple white AF1s, cleaned and ready for another summer. Classic crease pattern but no cracking or sole separation.",
      tags: ["sneakers", "white", "icon"],
      price: 38,
      cost: 12,
      floorPrice: 26,
      location: "C-02",
      listedAt: "2026-07-25T10:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-07-12",
      channels: { website: true, vinted: true, depop: true },
    }),
    build({
      sku: "VC-000431",
      name: "Ringer Tee",
      brand: "Stussy",
      category: "tops",
      size: "L",
      colour: "White / Black",
      material: "Cotton jersey",
      condition: "excellent",
      conditionNotes: "No visible wear. Print intact.",
      measurements: TOP_MEASUREMENTS,
      description:
        "90s-cut Stussy ringer tee with the script print. The cotton is still crisp, which is rare for these.",
      tags: ["streetwear", "tee", "90s"],
      price: 26,
      cost: 8,
      floorPrice: 18,
      location: "A-08",
      listedAt: "2026-08-15T09:30:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-08-08",
      isPick: true,
      channels: { website: true },
    }),
    build({
      sku: "VC-000358",
      name: "Polo Bear Knit",
      brand: "Ralph Lauren",
      category: "knitwear",
      size: "M",
      colour: "Cream",
      material: "Wool blend",
      condition: "excellent",
      conditionNotes: "No pulls, holes or fading. Dry cleaned.",
      measurements: TOP_MEASUREMENTS,
      description:
        "The Polo Bear jumper in cream. Dry cleaned and de-pilled before listing — it looks fresh off the rack.",
      tags: ["knit", "polo", "cream"],
      price: 58,
      cost: 20,
      floorPrice: 42,
      location: "A-03",
      listedAt: "2026-08-02T15:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-07-22",
      channels: { website: true, ebay: true },
    }),
    build({
      sku: "VC-000415",
      name: "Chore Coat",
      brand: "Dickies",
      category: "jackets",
      size: "S",
      colour: "Duck Brown",
      material: "Cotton twill",
      condition: "fair",
      conditionNotes: "Visible wear throughout including paint flecks on the sleeve. Still fully functional.",
      defects: ["Paint flecks on right sleeve", "Fading at collar"],
      measurements: JACKET_MEASUREMENTS,
      description:
        "A proper working chore coat with genuine paint flecks and honest wear. If you want one that looks like it has lived, this is it.",
      tags: ["workwear", "chore-coat", "worn"],
      price: 18,
      cost: 4,
      floorPrice: 10,
      location: "C-05",
      listedAt: "2026-07-18T11:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-07-05",
      channels: { website: true },
    }),
    build({
      sku: "VC-000392",
      name: "Nuptse 700 Vest",
      brand: "The North Face",
      category: "jackets",
      size: "M",
      colour: "TNF Red",
      material: "Nylon ripstop, down fill",
      condition: "very_good",
      conditionNotes: "Light wear, full loft, zip works smoothly.",
      measurements: JACKET_MEASUREMENTS,
      description:
        "Nuptse 700 gilet in the classic red. Puffs up properly and zips cleanly — the winter layer that goes over everything.",
      tags: ["outdoor", "gilet", "red"],
      price: 72,
      cost: 30,
      floorPrice: 54,
      location: "A-05",
      listedAt: "2026-08-09T10:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-07-29",
      featured: true,
      channels: { website: true, depop: true },
    }),
    build({
      sku: "VC-000427",
      name: "Baggy Skate Jeans",
      brand: "Stussy",
      category: "jeans",
      size: "32/30",
      colour: "Washed Blue",
      material: "Denim",
      condition: "very_good",
      conditionNotes: "Light fade only, no rips.",
      measurements: TROUSER_MEASUREMENTS,
      description:
        "Wide-leg skate cut in a soft washed blue. Sits low, stacks right, zero damage.",
      tags: ["skate", "denim", "baggy"],
      price: 48,
      cost: 16,
      floorPrice: 34,
      location: "B-09",
      listedAt: "2026-08-12T14:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-08-03",
      channels: { website: true, depop: true },
    }),
    build({
      sku: "VC-000406",
      name: "Track Jacket",
      brand: "Adidas",
      category: "jackets",
      size: "L",
      colour: "Black / White",
      material: "Polyester tricot",
      condition: "good",
      conditionNotes: "Some wear to cuffs, general light marks.",
      measurements: JACKET_MEASUREMENTS,
      description:
        "Three-stripe track top with the vintage cut. Collar stands up like it should, stripes are clean.",
      tags: ["sportswear", "three-stripes", "retro"],
      price: 24,
      cost: 7,
      floorPrice: 16,
      location: "B-05",
      listedAt: "2026-08-04T09:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-07-24",
      channels: { website: true, vinted: true },
    }),
    build({
      sku: "VC-000363",
      name: "Beta LT Shell",
      brand: "Arc'teryx",
      category: "jackets",
      size: "M",
      colour: "Forage Green",
      material: "3L Gore-Tex",
      condition: "very_good",
      conditionNotes: "DWR re-applied. No delamination, seams sealed.",
      measurements: JACKET_MEASUREMENTS,
      description:
        "Beta LT hardshell, recently re-treated and ready for the hills. All taped seams checked, no delamination anywhere.",
      tags: ["outdoor", "gore-tex", "shell"],
      price: 155,
      cost: 85,
      floorPrice: 120,
      location: "A-07",
      listedAt: "2026-08-10T08:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-07-30",
      featured: true,
      channels: { website: true },
    }),
    build({
      sku: "VC-000434",
      name: "Logo Beanie",
      brand: "Carhartt",
      category: "accessories",
      size: "One Size",
      colour: "Hamilton Brown",
      material: "Acrylic knit",
      condition: "new_without_tags",
      conditionNotes: "Unused, tags removed.",
      measurements: [],
      description: "Classic knit beanie in Hamilton brown. Never worn, tags just never survived the drawer.",
      tags: ["beanie", "winter", "knit"],
      price: 12,
      cost: 3,
      floorPrice: 8,
      location: "C-01",
      listedAt: "2026-08-15T12:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-08-09",
      channels: { website: true },
    }),
    build({
      sku: "VC-000372",
      name: "Retro X Fleece",
      brand: "Patagonia",
      category: "knitwear",
      size: "L",
      colour: "Forge Grey",
      material: "Polartec fleece",
      condition: "very_good",
      conditionNotes: "Light wear, windproof liner intact.",
      measurements: TOP_MEASUREMENTS,
      description:
        "Retro-X fleece jacket with the windproof liner. The collar still stands tall and the pile is deep.",
      tags: ["fleece", "outdoor", "retro"],
      price: 85,
      cost: 35,
      floorPrice: 62,
      location: "A-09",
      listedAt: "2026-08-07T13:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-07-27",
      channels: { website: true },
    }),
    build({
      sku: "VC-000441",
      name: "Oversized Graphic Tee",
      brand: "Vintage Band Merch",
      category: "vintage",
      size: "XL",
      colour: "Faded Black",
      material: "Heavy cotton",
      condition: "good",
      conditionNotes: "Faded exactly right. Two small pinholes on the back, photographed.",
      defects: ["Two small pinholes on the back"],
      measurements: TOP_MEASUREMENTS,
      description:
        "Single-stitch heavy cotton band tee from the early 2000s. The fade is authentic — this is what new tees are trying to copy.",
      tags: ["vintage", "band-tee", "single-stitch"],
      price: 32,
      cost: 10,
      floorPrice: 22,
      location: "C-04",
      listedAt: "2026-08-14T10:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-08-06",
      isPick: true,
      channels: { website: true, depop: true },
    }),
    build({
      sku: "VC-000395",
      name: "Cap",
      brand: "New Era",
      category: "accessories",
      size: "7 3/8",
      colour: "Navy",
      material: "Wool blend",
      condition: "excellent",
      conditionNotes: "Minimal wear, brim shape intact.",
      measurements: [],
      description: "Fitted New Era cap in navy. Brim keeps its curve, sweatband is clean.",
      tags: ["cap", "fitted", "navy"],
      price: 14,
      cost: 4,
      floorPrice: 9,
      location: "C-03",
      listedAt: "2026-08-05T15:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-07-25",
      channels: { website: true, vinted: true },
    }),
    build({
      sku: "VC-000409",
      name: "Cargo Trousers",
      brand: "Carhartt WIP",
      category: "trousers",
      size: "30/32",
      colour: "Dusty Olive",
      material: "Cotton twill",
      condition: "very_good",
      conditionNotes: "Light wear only, all pockets functional.",
      measurements: TROUSER_MEASUREMENTS,
      description:
        "Six-pocket cargos in a muted olive that goes with everything. All hardware intact, all pockets work.",
      tags: ["cargo", "olive", "twill"],
      price: 46,
      cost: 15,
      floorPrice: 32,
      location: "B-04",
      listedAt: "2026-08-03T11:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-07-21",
      channels: { website: true, depop: true },
    }),
    build({
      sku: "VC-000449",
      name: "Leather Bomber",
      brand: "Vintage Leather Co.",
      category: "vintage",
      size: "L",
      colour: "Dark Brown",
      material: "Genuine leather",
      condition: "good",
      conditionNotes: "Beautiful patina, lining has minor wear at the collar.",
      defects: ["Lining wear at collar"],
      measurements: JACKET_MEASUREMENTS,
      description:
        "90s leather bomber with a patina you cannot fake. Zip is solid, leather is supple, lining has honest age.",
      tags: ["vintage", "leather", "bomber"],
      price: 88,
      cost: 38,
      floorPrice: 64,
      location: "C-06",
      listedAt: "2026-08-11T16:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-08-01",
      channels: { website: true, ebay: true },
    }),
    build({
      sku: "VC-000422",
      name: "Hooded Sweatshirt",
      brand: "Champion",
      category: "hoodies",
      size: "S",
      colour: "Oxford Grey",
      material: "Reverse weave",
      condition: "very_good",
      conditionNotes: "Light wash wear, ribbed cuffs intact.",
      measurements: TOP_MEASUREMENTS,
      description:
        "Reverse weave hoodie in oxford grey. The fabric that refuses to lose its shape, and it hasn't.",
      tags: ["hoodie", "reverse-weave", "grey"],
      price: 30,
      cost: 10,
      floorPrice: 21,
      location: "B-08",
      listedAt: "2026-08-09T09:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-07-29",
      channels: { website: true },
    }),
    build({
      sku: "VC-000456",
      name: "Gas Station Cap",
      brand: "Vintage Workwear",
      category: "vintage",
      size: "Adjustable",
      colour: "Faded Red",
      material: "Cotton twill",
      condition: "fair",
      conditionNotes: "Heavy fade and sweat stains around the band. The charm is real.",
      defects: ["Fading", "Band staining"],
      measurements: [],
      description:
        "A genuine old garage cap with the fade only decades of sun can produce. Adjustable strap, no tears.",
      tags: ["vintage", "cap", "workwear"],
      price: 15,
      cost: 3,
      floorPrice: 8,
      location: "C-07",
      listedAt: "2026-07-28T10:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-07-15",
      channels: { website: true },
    }),
    build({
      sku: "VC-000401",
      name: "90s Windbreaker",
      brand: "Nike",
      category: "vintage",
      size: "M",
      colour: "Purple / Teal",
      material: "Nylon",
      condition: "good",
      conditionNotes: "Some creasing and light marks. Colours still vivid.",
      measurements: JACKET_MEASUREMENTS,
      description:
        "Proper 90s windbreaker in the loudest colourway we could find. Cuffs and waistband elastic still spring back.",
      tags: ["vintage", "90s", "windbreaker"],
      price: 36,
      cost: 11,
      floorPrice: 24,
      location: "C-08",
      listedAt: "2026-08-01T14:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-07-19",
      channels: { website: true, vinted: true },
    }),
    build({
      sku: "VC-000384",
      name: "Logo Cap",
      brand: "Supreme",
      category: "accessories",
      size: "Adjustable",
      colour: "Black",
      material: "Cotton twill",
      condition: "new_with_tags",
      conditionNotes: "Unused with original tags attached.",
      measurements: [],
      description: "Camps cap in black, still tagged. Crown is crisp, strap untouched.",
      tags: ["cap", "streetwear", "black"],
      price: 55,
      cost: 30,
      floorPrice: 40,
      location: "A-10",
      listedAt: "2026-08-16T09:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-08-12",
      isPick: true,
      channels: { website: true },
    }),
    build({
      sku: "VC-000377",
      name: "Denim Trucker Jacket",
      brand: "Levi's",
      category: "jackets",
      size: "M",
      colour: "Washed Blue",
      material: "Denim",
      condition: "very_good",
      conditionNotes: "Even fade, no wear-through anywhere.",
      measurements: JACKET_MEASUREMENTS,
      description:
        "Type III trucker with the perfect all-over fade and no weak points. Buttons all original and firm.",
      tags: ["denim", "trucker", "classic"],
      price: 62,
      cost: 20,
      floorPrice: 44,
      location: "B-02",
      listedAt: "2026-08-06T08:00:00Z",
      acquisitionSource: "Private seller",
      purchaseDate: "2026-07-26",
      channels: { website: true, vinted: true },
    }),
    build({
      sku: "VC-000365",
      name: "Arctic Parka - Sold",
      brand: "The North Face",
      category: "jackets",
      size: "M",
      colour: "Navy",
      material: "Nylon shell, down fill",
      condition: "excellent",
      conditionNotes: "SOLD - kept for archive.",
      measurements: JACKET_MEASUREMENTS,
      description: "Sold piece shown on the homepage recently sold rail.",
      tags: ["winter", "parka"],
      price: 110,
      cost: 45,
      floorPrice: 80,
      status: "SOLD",
      location: "OUT",
      listedAt: "2026-07-10T10:00:00Z",
      soldAt: "2026-08-14T18:20:00Z",
      channels: { website: true },
    }),
    build({
      sku: "VC-000362",
      name: "Puffer Jacket - Sold",
      brand: "The North Face",
      category: "jackets",
      size: "S",
      colour: "Black",
      material: "Nylon, down fill",
      condition: "very_good",
      conditionNotes: "SOLD - kept for archive.",
      measurements: JACKET_MEASUREMENTS,
      description: "Sold piece shown on the homepage recently sold rail.",
      tags: ["winter", "puffer"],
      price: 78,
      cost: 30,
      floorPrice: 55,
      status: "SOLD",
      location: "OUT",
      listedAt: "2026-07-06T09:00:00Z",
      soldAt: "2026-08-13T11:05:00Z",
      channels: { website: true },
    }),
    build({
      sku: "VC-000359",
      name: "Fleece Hoodie - Sold",
      brand: "Patagonia",
      category: "hoodies",
      size: "M",
      colour: "Tan",
      material: "Fleece",
      condition: "excellent",
      conditionNotes: "SOLD - kept for archive.",
      measurements: TOP_MEASUREMENTS,
      description: "Sold piece shown on the homepage recently sold rail.",
      tags: ["fleece", "outdoor"],
      price: 55,
      cost: 20,
      floorPrice: 38,
      status: "SOLD",
      location: "OUT",
      listedAt: "2026-07-14T12:00:00Z",
      soldAt: "2026-08-12T09:40:00Z",
      channels: { website: true },
    }),
    build({
      sku: "VC-000354",
      name: "Denim Jacket - Sold",
      brand: "Levi's",
      category: "jackets",
      size: "L",
      colour: "Mid Blue",
      material: "Denim",
      condition: "good",
      conditionNotes: "SOLD - kept for archive.",
      measurements: JACKET_MEASUREMENTS,
      description: "Sold piece shown on the homepage recently sold rail.",
      tags: ["denim", "trucker"],
      price: 40,
      cost: 12,
      floorPrice: 26,
      status: "SOLD",
      location: "OUT",
      listedAt: "2026-07-02T15:00:00Z",
      soldAt: "2026-08-10T16:45:00Z",
      channels: { website: true },
    }),
  ];
}
